### ISSUE TITLE
Different behaviour between "item-state read" and "item-state -read"?

### ISSUE THREAD

**Issue by Narrat** [themoken/canto-curses#17]
I have two keys set with this options (h/l dunno if they're defaults)  + global_transform filter_read

Problem:
item-state read: marks the item as read, nothing more
item-state -read: unmark the item as read and kicks in the filter_read. So if I want to unmark more than one item, but not the whole tag I would need to deactivate the filter.

Is there some default setting set for h? Did I use the wrong option? I don't want that the filter kicks in while setting feeds as unread.

**Comment by themoken** [comment]
My guess is that you're still updating with an interval, and item-state -read causes a tag change that then updates your screen. This isn't good behavior (although it's still supported) which is why 0.9.0 changed the default to manual, i.e. you have to request an update.

If you do ":set update.auto.enabled False" do you still get this bad behavior?

**Comment by themoken** [comment]
Yeah, the interval won't do any harm if it's disabled.

Not really clear on what you're seeing then though. Locally, if I just do those commands, it behaves as expected (one item changes color, basically).

Do you think you can reproduce with a git version of `canto-curses -v` and gist or email the .canto-ng/curses_log to me (jack@codezen.org)?

**Comment by Narrat** [comment]
With latest git it isn't occuring anymore.

(But I was greeted by this message (daemon is also latest git)
https://paste.archlinux.de/s8qQVV/
https://gist.github.com/Narrat/15474b6dbdb3448a07f8#file-cc 
But cannot be much of problem, as I cannot reproduce it)

Switching back to 0.9.0 and the problem appears again. So I assume it is fixed as it isn't happening with latest git :)

**Comment by themoken** [comment]
Okay. I'm closing this and am probably going to put out 0.9.1 pretty soon.

I've never seen that "Failed to parse" message before, but it stems from JSON failing to parse something which shouldn't happen - at least not on the curses side. If you see it again, open a separate bug.
