### ISSUE TITLE
Feature Request: option to strip HTML tags from title

### ISSUE THREAD

**Issue by kjellgren** [themoken/canto-curses#18]
Feed from Jira have HTML in title that make it hard to read with canto-curses 
Simple remove like this is working fine
```
def remove_html_markup(s):
    tag = False
    quote = False
    out = ""
    for c in s:
        if c == '<' and not quote:
            tag = True
        elif c == '>' and not quote:
            tag = False
        elif (c == '"' or c == "'") and tag:
            quote = not quote
        elif not tag:
            out = out + c
    return out

**Comment by themoken** [comment]
You've gotta be pretty careful with this sort of thing as there's no reason < and > wouldn't show up in a real piece of text sent through prep_for_display (which is where I assume you made that change).

I grabbed a test JIRA feed from their site ( https://jira.atlassian.com/sr/jira.issueviews:searchrequest-rss/temp/SearchRequest.xml?jqlQuery=text+~+%22test%22&tempMax=1000 ) and it didn't have raw HTML anywhere, although each issue's reader text was terribly formatted.

Can you provide the offending source XML? I'm curious how the content is declared.

**Comment by kjellgren** [comment]
Here is a example (Jira version 6.1.7)
```
Title: <a class="activity-item-user activity-item-author" href="https://jira.3s.intern/secure/ViewProfile.jspa?name=shamlooa">Ahm S</a> created       <a href="https://jira.3s.intern/browse/UNIX-23"><span class="resolved-link">UNIX-23</span> - Reinstall ltest24</a>
Title: <a class="activity-item-user activity-item-author" href="https://jira.3s.intern/secure/ViewProfile.jspa?name=kjellgrb">Ben K</a> closed       <a href="https://jira.3s.intern/browse/UNIX-22"><span class="resolved-link">UNIX-22</span> - Having trouble while logging into ztest108</a>

(using rsstail command)

**Comment by kjellgren** [comment]
Both RSS and Atom feeds exits in Jira.

Example of raw atom:title with HTML content:

```
<title type="html">&lt;a href="https://jira.3s.intern/secure/ViewProfile.jspa?name=kjellgrb" class="activity-item-user activity-item-author">Ben K&lt;/a>
closed &lt;a href="https://jira.3s.intern/browse/UNIX-23">&lt;span class='resolved-link'>UNIX-23&lt;/span> - Reinstall&lt;/a></title>

**Comment by themoken** [comment]
Hey. So I finally made a plugin to clean up story titles and I integrated your function into it (with credit and a reference here). Reopen this issue if you run git and the plugin doesn't work, but since it's using your solution it should be okay.
