### ISSUE TITLE
Indicator counter reacts on "mark unread"

### ISSUE THREAD

**Issue by Narrat** [themoken/canto-curses#19]
It's currently possible to "manipulate" the new indicator by simply marking an item unread again (Even using the same item again and again doing "read-->unread-->read.....")

While not really tragic I suppose it contradicts the purpose you mentioned in your blogpost from 17.12.2014
"A minor change to canto-curses is that the tag status line now includes a grey indicator (similar to the blue indicator for unread items) for items that have been updated, but haven’t been displayed yet."

But manually marking an item unread is an item which is already displayed so normally it shouldn't be displayed.

**Comment by themoken** [comment]
This should be fixed in 0.9.1 (git)
