### ISSUE TITLE
How to specify link to follow

### ISSUE THREAD

**Issue by Buridan** [themoken/canto-curses#27]
I am using canto-curses for the first time and i have some habits from the Previous implementation of canto.
What is now the equivalent of goto (g + linkNumber + enter) on canto-curses?

**Comment by themoken** [comment]
:goto [link number]

**Comment by Buridan** [comment]
I'm supposed to write :goto # any time i need to follow a link? There is no shortcut anymore for it?

**Comment by themoken** [comment]
the 'g' key works for the main link (link 0), and you can setup a shortcut for the others if you want. With the reader open doing

:bind 1 goto 1

For example, will bind the '1' key to go to link 1, and that will be remembered automatically.
