### ISSUE TITLE
Have arrow keys "left" and "right" bind to "-read" and "read" by default

### ISSUE THREAD

**Issue by devhell** [themoken/canto-curses#29]
This is obviously a subjective proposition. However, I find it rather intuitive to be able to use the left and right arrows to mark an item read or unread. Since there seems to be no default setting for this sort of behavior I thought this might be something worth looking into?

Obviously users can bind it themselves, I just thought it might be even more convenient if this was already the case.

Thanks! :-)

**Comment by ewancoder** [comment]
Well, I find it intuitive to use h/l keys to mark as read/unread, and j/k keys to move up and down. This way you get vim-like movement and your hand doesn't leave home row. So I guess this is subjective opinion of the each person.

**Comment by devhell** [comment]
@ewancoder Exactly, I just thought that it might be good to have some default setting which pertains to this use-case.

**Comment by Buridan** [comment]
That's a good solution to keep old canto's legacy.

**Comment by themoken** [comment]
I just pushed a commit to make h/left mark read and l/right mark unread. It will only be set by default for new configs, or if you do ":reset-config taglist" to reset the taglist config to default. Alternatively, as mentioned, this can be done manually with :bind.

**Comment by devhell** [comment]
@themoken Thanks a lot!
