### ISSUE TITLE
daemon-log showing traceback calls

### ISSUE THREAD

**Issue by devhell** [themoken/canto-curses#30]
This is happening even with a completely fresh instance of canto. Note that the paths look weird because of the way [NixOS](https://nixos.org/) handles them (I'm the maintainer for canto on this distribution). Therefore please disregard the path "weirdness".

```
Traceback (most recent call last):
  File "/nix/store/i1ngys8ag4mc28hi9vk4s5smw91g15na-canto-daemon-0.9.3/lib/python3.4/site-packages/canto_next/server.py", line 40, in read_loop
    d = self.do_read(conn)
  File "/nix/store/i1ngys8ag4mc28hi9vk4s5smw91g15na-canto-daemon-0.9.3/lib/python3.4/site-packages/canto_next/protocol.py", line 214, in do_read
    r = self._do_read(conn, timeout)
  File "/nix/store/i1ngys8ag4mc28hi9vk4s5smw91g15na-canto-daemon-0.9.3/lib/python3.4/site-packages/canto_next/protocol.py", line 250, in _do_read
    size = struct.unpack('!q', conn.recv(8))[0]
struct.error: unpack requires a bytes object of length 8
```

Other than the callbacks in the `daemon-log` it doesn't seem that canto is suffering functionality, all feeds display fine and work as expected. So I'm not exactly sure if the above traceback is expected or not.

**Comment by themoken** [comment]
Yeah, it's "expected" in that it happens any time a client disconnects and I just didn't get around to shutting it up. Harmless, but I'll quiet it down.

**Comment by devhell** [comment]
@themoken Ah! Very cool, thanks for the info! Do you want me to close this issue then?

**Comment by themoken** [comment]
Nah, I'll close it when a fix is in git.

**Comment by devhell** [comment]
:+1: :beers:

**Comment by themoken** [comment]
Fix in git. https://github.com/themoken/canto-next/commit/8b0e34b8b828cb426a2cd05b815e2460423aca9c

**Comment by devhell** [comment]
@themoken Much appreciated!
