### ISSUE TITLE
show-category does not work as expected

### ISSUE THREAD

**Issue by rumpelsepp** [themoken/canto-curses#31]
I have two feeds in a category `heise`. When I want to show that category there seem to be some problems:

![screenshot from 2015-07-21 10-42-18](https://cloud.githubusercontent.com/assets/1961699/8796461/42a9d394-2f95-11e5-9f6d-d31eb959a00e.png)
![screenshot from 2015-07-21 10-42-34](https://cloud.githubusercontent.com/assets/1961699/8796460/42a70196-2f95-11e5-81d6-2ce3b9cdfea6.png)

After `:show-category heise`:

![screenshot from 2015-07-21 10-42-53](https://cloud.githubusercontent.com/assets/1961699/8796459/42a67140-2f95-11e5-8180-25da346688ca.png)

I expect that canto shows the two feeds which are categorized in `heise`. It seems that canto only shows the selected item instead.

**Comment by themoken** [comment]
Hmmm, seems to be working here, is your version up to date?

:show-category is actually a transform change on the daemon side, so c-c dumps all your items and then fetches just the ones in the category. It looks like your last screenshot is half way there (i.e. c-c has forgotten everything but your selection - which it should always have) but there should be items incoming, or items pending. If you could reproduce with `canto-curses -v` and then pastebin your ~/.config/canto/curses-log (or ~/.canto-ng/curses-log if that exists) somewhere, or email it to me (jack@codezen.org), I should be able to tell what went wrong.

**Comment by rumpelsepp** [comment]
I have send you an email. My version:

```
$ pacman -Qs canto
local/canto-curses 0.9.3-1
    ncurses user interface for canto-daemon
local/canto-daemon 0.9.1-1
    News aggregator for Atom/RSS/RDF
```

**Comment by themoken** [comment]
Email received, I'll take a look, but if you could checkout the git versions (the AUR has packages canto-curses-git and canto-next-git) of both, they might solve your problem. A lot of fixes and tweaks have been made since your versions.

**Comment by rumpelsepp** [comment]
Ok. I realized that the package in AUR3 is outdated; due to the transition to AUR4. I updated manually to the most recent version. Now it works! thanks

**Comment by themoken** [comment]
Excellent.

**Comment by rumpelsepp** [comment]
Just posted simultaneously. Thanks for your answer; since it works now, there is no need to waste time to read my logs any more. :)

**Comment by Narrat** [comment]
@rumpelsepp: Jeah, I don't update the AUR3 versions, as those changes will be lost in a few days and I figured people were mostly using the new one and kicked the setup I had to upload the tarballs.
