### ISSUE TITLE
browser.path gets reset to firefox everytime canto-curses is started

### ISSUE THREAD

**Issue by devhell** [themoken/canto-curses#32]
When explicitly setting the browser to chromium using `:set browser.path chromium` the value is saved in `~/.config/canto/conf` as expected (and works as expected!). However, after quitting and restarting `canto-curses` the value changes to `firefox` instead, and indeed it'll start `firefox` when I wish to open a feed.

Am I doing something wrong?

Thanks!

**Comment by themoken** [comment]
You wouldn't have happened to put autocmd.py into your plugins without configuring it, would you?

**Comment by devhell** [comment]
And there we have it. I'm a moron.
Thank you so much, I didn't even think of that possibility. Apologies for the noise. :-/

**Comment by themoken** [comment]
No worries man, I should probably put an ENABLE variable at the top of the plugins (uniformly) for just this reason.
