### ISSUE TITLE
Canto-curses won't load

### ISSUE THREAD

**Issue by Buridan** [themoken/canto-curses#33]
There is an error when i try to start canto-curses:
``Traceback (most recent call last):

     File "/usr/bin/canto-curses", line 3, in <module>

     from canto_curses.main import CantoCurses

     ImportError: No module named 'canto_curses'
``

**Comment by themoken** [comment]
Python probably got updated and your new version doesn't have it installed.
Try reinstalling.

- Jack

On Tue, Oct 6, 2015 at 1:46 PM, Paul-emmanuel LETT <notifications@github.com

**Comment by Buridan** [comment]
Now it works.
