### ISSUE TITLE
Feature request : filter

### ISSUE THREAD

**Issue by Maeda1** [themoken/canto-curses#34]
Hi !

I think it should be a good idea to create a filter (or at least an option for all feeds) that could lead to display only a number of lines on each feed.

The choice of how many lines is displayed would be great.

Then, if there are not many feeds, it will permit to users to uncollapse all of the feeds and see in one time (one display) if there are newer articles.

Thanks.

**Comment by themoken** [comment]
Select an item in the tag and then do

    :set tag.transform ItemLimit(10)

For example, to limit that tag to 10 items displayed. You will have to refresh (Ctrl+r) to actually see it change however. You can then change it by issuing the same command with a different number, or cancel it by setting it to None.

**Comment by Maeda1** [comment]
Hi !

Perfect :). Works like expected.
You should put this in the Canto's Manual page ;)

Thanks.
