### ISSUE TITLE
Datetime column

### ISSUE THREAD

**Issue by NicolasWebDev** [themoken/canto-curses#35]
I have been looking everywhere I could, and I cannot find a way to find a datetime associated to the feeds.

I think it would be nice to have this info both in the taglist view, along within the Reader view.

Is there already a way to do that?

**Comment by themoken** [comment]
I just added an example to the reader-extras.py plugin that adds the date an item was published or updated... but as with all things RSS it only works when the feed creator actually bothers to put that data into the item (it's really hit or miss).

I'm not sure what you'd want in the tag list view... the date in the title of the item seems really messy (and again, would only work on some feeds) or do you mean the feed date in the tag header ([-] Slashdot [100] updated 01/20/16)?

**Comment by Sathors** [comment]
Actually I was more thinking of the datetime canto-next was getting the feed at.
It would not exactly represent the feed time per se (knowing that updating is done every s seconds), but at least it would enable to give some chronology to the taglist.

In the case that may be possible, I was thinking of another column in the taglist, or separated with a tab.
We may also imagine separating the date and the hour in two different columns, enabling the user to configure their position (between date, time, header).
01/20/16    |    08:09    |    [-] Slashdot [100]

**Comment by themoken** [comment]
Ah, I see, the last time the daemon fetched not when the story was updated. Well, the daemon does track that, but it pretty much only uses it internally. Would be nice to have... I'll take a look at making this possible.

**Comment by Sathors** [comment]
Thanks @themoken , I'll keep waiting for your update then.
