### ISSUE TITLE
[Bug] Video links are not parsed anymore

### ISSUE THREAD

**Issue by Buridan** [themoken/canto-curses#36]
hi,
This last week i can't read video links anymore on my feed.
There is an example:
http://sprunge.us/ORHA (xml element)

http://bit.ly/1Pz9xss (xml corectly parsed)

http://bit.ly/23IyhER (xml parsed by canto) // it lacks video links

I don't know what happened.

Regards,
Buridan

**Comment by themoken** [comment]
Hmm, canto uses feedparser so it's possible that there was an update that broke this, but have you maybe turned off showing enclosures (media files)... the command is :show-enclosures to toggle their visibility and it's bound to 'e' in the reader by default.

**Comment by Buridan** [comment]
That's it!
Thank you very much for your quick answer.
