### ISSUE TITLE
Auto-generated canto.conf file uses non-existent feed 

### ISSUE THREAD

**Issue by DistantParadox** [themoken/canto-curses#38]
Canto Version:  Canto v 0.7.10 (sh:)     (The version from running `sudo apt-get install canto` in Linux Mint)
Operating System: Linux 4.2.0-30-generic #36~14.04.1~Ubuntu 86_64 (Linux Mint)

Issue:

Upon starting canto for the first time, it auto generates the ~/.canto/conf.py.example file.  In this file, it specifies the lines:

`add("http://codezen.org/canto/feeds/latest")`
`add("http://kerneltrap.org/node/feed")`

However, the first one points to a feed that does not exist, and the second one's URL times out.  Upon running `canto -u`, it gives the following errors:

`Exception trying to get feed http://codezen.org/canto/feeds/latest : HTTP Error 404: Not Found`
`Exception trying to get feed http://kerneltrap.org/node/feed : <urlopen error timed out>`

Try going to [http://codezen.org/canto/feeds/latest](http://codezen.org/canto/feeds/latest) and it will tell you that the page can't be found.  Also, try going to [http://kerneltrap.org/node/feed](http://kerneltrap.org/node/feed) and the page will continuously load.

A possible replacement for this could be using [http://www.theguardian.com/international/rss](http://www.theguardian.com/international/rss) instead, or a different feed that works.

**Comment by themoken** [comment]
That version of canto is five years old, the latest code uses proper feeds.
