### ISSUE TITLE
Since 3.5.2 non ascii chars missing

### ISSUE THREAD

**Issue by Narrat** [themoken/canto-curses#39]
Kinda curious. After the update of python to the latest version (3.5.2) chars like ä, ö, ü won't be displayed anymore.
Nothing found in the logs, so dunno how to provide information about this.

**Comment by Narrat** [comment]
![1467802913](https://cloud.githubusercontent.com/assets/2787518/16616036/da71559a-437a-11e6-89c1-7c636600f7ae.png)

In red encircled should be a char (and they existed in the past).
And it happens for every feed

**Comment by themoken** [comment]
This isn't canto or Python breakage AFAICT, I can see those characters just fine with latest canto-curses and Python 3.5.2 here on Arch and even using Golem.de feeds.

Things I would try, although they're longshots:

- check `locale`, /etc/locale.gen, etc. to make sure your terminal locale didn't change. Canto uses LC_ALL, and it should probably be a UTF-8 locale regardless of base language.

- check that the locale has been generated (`sudo locale-gen`)

- try canto-curses in a known good terminal, like uxterm or urxvt (both work here)

If these don't work it would be interesting to know for certain that downgrading to Python 3.5.1 fixes it, or if other rich console apps (like elinks) are having the same issue.

**Comment by Narrat** [comment]
Happens with every terminal and locales are generated.
But the LC_ALL seems to be case.
Everything is set with the locale of choice. LC_ALL is empty.. The hell?

**Comment by Narrat** [comment]
To make it even more curios. Downgrading to 3.5.1 and the chars appear again

**Comment by themoken** [comment]
Did setting LC_ALL fix it on 3.5.2?

**Comment by Narrat** [comment]
Nope. Chars are still missing, hm

**Comment by themoken** [comment]
Looking through the 3.5.2 changelog, here's a shot in the dark: what does this command output on either version?

`python -c 'import sys; print(sys.stdout.encoding, sys.stdout.errors)'`

Here I get "UTF-8 strict"

**Comment by Narrat** [comment]
For both versions the same result:

``` shell
$ python --version
Python 3.5.1
~ $ python -c 'import sys; print(sys.stdout.encoding, sys.stdout.errors)'
UTF-8 strict
~ $ python --version                                                     
Python 3.5.2
~ $ python -c 'import sys; print(sys.stdout.encoding, sys.stdout.errors)'
UTF-8 strict
```
Maybe it's an error within the i686 package

**Comment by themoken** [comment]
Possible, I'm totally 64 bit here.

**Comment by Narrat** [comment]
And doesn't happen for me on armv7h too.
So, just i686 until now

**Comment by Narrat** [comment]
After the python 3.6 update on i686 the non ascii chars still are missing, but this time "placeholder" like "you used the wrong encoding to decode this stuff" appear.
But as armv7h and my new x86_64 machine show it totally fine, it's imo not worth to track the issue any longer. So closing it
