### ISSUE TITLE
':del Reddit' unsubs random other feed

### ISSUE THREAD

**Issue by AdrianSchurz** [themoken/canto-curses#42]
Greetings,

(system: Arch-Linux, at most a week since last update, used pkg: [canto-curses-git 0.9.7-1](https://aur.archlinux.org/packages/canto-curses-git/))

while trying to debug some other issues I purged the package + config
`pacman -Rns canto-curses-git; rm -r ~/.config/canto`
and reinstalled the package from aur. It comes preinstalled with a few feeds, one of them being reddit. Trying to delete them one by one led me to fire up the client and type.
`:del Reddit`
(actually, I did this twice, being confused and trying again before stopping at the error message - the one preinstalled feed I am not mentioning here was therefore the first to be deleted)
As a result the client displays

> 
Invalid tag : 'Reddit'
Unsubscribing from http://rss.slashdot.org/slashdot/Slashdot

Slashdot is promptly unsubbed and not displayed any more although that string that is displayed in the client, and that I always understood to be the tag (I am squarely prepared to be embarrassed here), as well as the only other non-url item reported by
`canto-remote listfeeds`
actually matches the string "Reddit" rather well.

Is this intended?
It greatly hampers my ability to investigate other issues I've encountered in a reasonable time because it modifies my feed list in a way not speedily investigated or recovered.

If I remember correctly, this operation once in the past displayed a rudimentary dialog asking for confirmation to unsub from a random other feed instead that I could instruct to do nothing by hitting "n". Do not quote me on that one, though, memory is fallible and I would not know how to reproduce.

Best regards

**Comment by themoken** [comment]
This is definitely a bug. First because it's not recognizing "Reddit" which, since you're using the default config, is the exact name. And then second, since it doesn't recognize the name it attempts to limp on with the first tag it knows about. This is good behavior when, for example, you open the reader without an item selected (it chooses the first tag, first item), but obviously that's really shitty behavior when you're deleting.
