### ISSUE TITLE
libreadline.so.6 not found

### ISSUE THREAD

**Issue by Maeda1** [themoken/canto-curses#43]
Hi !

I just upgraded my Archlinux system, and canto-curses doesn't work anymore :
`Traceback (most recent call last):
  File "/usr/bin/canto-curses", line 3, in <module>
    from canto_curses.main import CantoCurses
  File "/usr/lib/python3.5/site-packages/canto_curses/main.py", line 18, in <module>
    from .gui import CantoCursesGui, GraphicalLog
  File "/usr/lib/python3.5/site-packages/canto_curses/gui.py", line 12, in <module>
    from .tag import alltags
  File "/usr/lib/python3.5/site-packages/canto_curses/tag.py", line 14, in <module>
    from .theme import FakePad, WrapPad, theme_print, theme_reset, theme_border, prep_for_display
  File "/usr/lib/python3.5/site-packages/canto_curses/theme.py", line 10, in <module>
    from .widecurse import waddch, wcwidth
ImportError: libreadline.so.6: cannot open shared object file: No such file or directory`

By searching file, I found this :
`/usr/lib/libreadline.so -> libreadline.so.7`

Miss something ? Should I create a symbolic link ?

Thanks.

**Comment by Narrat** [comment]
Just rebuild the package

**Comment by Maeda1** [comment]
For both canto-next and canto-curses, I got :

`running install
running build
running build_py
copying canto_curses/main.py -> build/lib.linux-x86_64-3.5/canto_curses
running build_ext
running build_scripts
running install_lib
copying build/lib.linux-x86_64-3.5/canto_curses/main.py -> /usr/lib/python3.5/site-packages/canto_curses
byte-compiling /usr/lib/python3.5/site-packages/canto_curses/main.py to main.cpython-35.pyc
running install_scripts
changing mode of /usr/bin/canto-curses to 755
running install_data
fatal: aucun nom trouvé, impossible de décrire quoi que ce soit.
Command '['git', 'describe']' returned non-zero exit status 128
running install_egg_info
Removing /usr/lib/python3.5/site-packages/Canto_curses-0.9.6-py3.5.egg-info
Writing /usr/lib/python3.5/site-packages/Canto_curses-0.9.6-py3.5.egg-info`

Using 4.8.11-1-ARCH

**Comment by Narrat** [comment]
What is the meaning of the french part in this error message.
And what is your method? Using a pkgbuild or manual build?

**Comment by Maeda1** [comment]
The french part means : no name found, impossible to describe anything.
I downloaded the files on this git repository and execute the command line as specified on the README.

**Comment by Narrat** [comment]
Did you use git before? The error (128) can appear if no global config file for git exists (email and name).

**Comment by Maeda1** [comment]
I tried with the aur pkgbuild, but it seems that it doesn't want to install as files are already present, like :
canto-next-git : /usr/lib/systemd/user/canto-daemon.service
canto-next-git : /usr/lib/python3.5/site-packages/canto_next/transform.py
canto-next-git : /usr/bin/canto-daemon
...

Maybe I can simply delete them before doing an `makepg -sri` ?

**Comment by Narrat** [comment]
Dunno what you have done, to achieve that ;)
But in that case, you can use forced install to override existing files

``` sh
$ makepkg -sr
# pacman -U --force canto-next-git-...
```

**Comment by Maeda1** [comment]
Indeed, problem solved with `pacman -U --force <name_of_package_created_by_makepkg>`

Big thanks 👍
