### ISSUE TITLE
Ghost feed not listed in frontend

### ISSUE THREAD

**Issue by Maeda1** [themoken/canto-curses#44]
Hi !

I have a feed added that doesn't show up anymore in the list.
I can't _:del_ it as I don't see the feed.
If I add it again, here is the curses-log file : 

_COMMON -> Adding feed http://www.purepeople.com/rss/news_t0.xml - Purepeople - Toutes les news
ERRORS!
[feeds][12][name] -> Purepeople - Toutes les news: Feed name already used!
[feeds][12][name] -> Purepeople - Toutes les news: Set but invalid and required_

The feeds files in .config/canto/ seems to be crypted.
The _canto-remote listfeeds_ show the entry on #6, but if I _:del 6_ it delete another feed.

Any idea ?

**Comment by Narrat** [comment]
Well, you can still delete the feed with canto-remote directly.

Could you upload your canto config?
And yes. The feed file is gzipped (and json iirc)

**Comment by Maeda1** [comment]
I delete the { part } in the **conf** file, and then reimported by **:add** command, all's right the feed show up again.

Maybe a consequence of compiling the last version ?

I can send you the old **conf** file (I backed up it before all changes) but not in public section.

**Comment by Narrat** [comment]
Cannot remember if such a problem appeared, just due to compiling a new version. I would rule that out.
My thinking was, that somehow a keybind, was used which caused, that the specific feed got filtered.
Which could appear in the config.

But as it is "solved", your decision if I should take a view on the old config.
Maybe you could diff old and new config, if something of interest appears.

**Comment by Maeda1** [comment]
Good idea.

I check the diff, and indeed, the URL for this feed doesn't work anymore. Then I can't delete it from _curses frontend_, need to do it directly in the **conf** file.
From _curses frontend_, why is it impossible to overwrite an existing feed entry with another URL ?

**Comment by Narrat** [comment]
Well, there was a problem with deleting feeds from canto-curses, and depending what version you installed (latest stable release, or git master/HEAD) the problem could still exist for you.

Regarding your question. I cannot tell. Maybe an oversight, maybe to prevent overwriting a feed by accident.

**Comment by Maeda1** [comment]
OK. I understand.
