### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by for-coursera** [themoken/canto-curses#46]
Got the following error while compiling:

    $ git clone https://github.com/themoken/canto-curses.git
    Cloning into 'canto-curses'...
    remote: Counting objects: 3477, done.
    remote: Total 3477 (delta 0), reused 0 (delta 0), pack-reused 3477
    Receiving objects: 100% (3477/3477), 1.24 MiB | 497.00 KiB/s, done.
    Resolving deltas: 100% (2380/2380), done.
    CHecking connectivity... done.
    $ cd canto-curses/
    $ python3 setup.py install --prefix=~/usr/local/bin/canto
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.8-x86_64-3.5
    creating build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/__init__.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/color.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/command.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/config.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/gui.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/guibase.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/html.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/input.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/locks.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/main.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/reader.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/screen.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/story.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/subthread.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/tag.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/tagcore.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/taglist.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/text.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    copying canto_curses/theme.py -> build/lib.macosx-10.8-x86_64-3.5/canto_curses
    running build_ext
    building 'canto_curses.widecurse' extension
    creating build/temp.macosx-10.8-x86_64-3.5
    creating build/temp.macosx-10.8-x86_64-3.5/canto_curses
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG o
    canto_curses/widecurse.c:63:4: warning: implicit declaration of function 'waddwstr' is
          invalid in C99 [-Wimplicit-function-declaration]
                            waddwstr(win, dest);
                            ^
    canto_curses/widecurse.c:200:11: warning: comparison of constant 9223372036854775807 with
          expression of type 'int' is always false
          [-Wtautological-constant-out-of-range-compare]
                    if (len > PY_SSIZE_T_MAX) {
                        ~~~ ^ ~~~~~~~~~~~~~~
    2 warnings generated.
    clang -bundle -undefined dynamic_lookup build/temp.macosx-10.8-x86_64-3.5/canto_curses/wio
    ld: warning: directory not found for option '-L/opt/local/lib'
    ld: library not found for -lncursesw
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'clang' failed with exit status 1

**Comment by Narrat** [comment]
Do you have ncurses installed? It provides on most distributions the missing library
