### ISSUE TITLE
Canto Curses colour problem with 'Solarized dark' in GNOME Terminal.

### ISSUE THREAD

**Issue by zayuim** [themoken/canto-curses#47]
When GNOME terminal is set to use 'Solarized dark' as the background and text colour and then Solarized as the palette, The article title text becomes unreadable.
![screenshot from 2017-09-16 13-53-05](https://user-images.githubusercontent.com/22744080/30508988-aae3c518-9ae7-11e7-8765-ef2e301b8d64.png)

However 'Solarized light' is just fine.
![screenshot from 2017-09-16 13-53-13](https://user-images.githubusercontent.com/22744080/30508994-c01dbf42-9ae7-11e7-9f62-5853a77ef764.png)

**Comment by themoken** [comment]
Sorry it's taken me a bit to get to this, but have you tried customizing Canto's color scheme with the ':color' command?
