### ISSUE TITLE
All tags empty

### ISSUE THREAD

**Issue by beemo-ceniza** [themoken/canto-curses#48]
So after i mark all the items as read this message appears and nothing else

> All tags empty

i would like to still see the items marked as read so i can click them even read i was unable to figure it out using the manual

**Comment by themoken** [comment]
By default read items are filtered. The setting you're looking for is the "global transform" which applies to all items. To disable this from inside canto-curses do:

    :set global_transform None

**Comment by beemo-ceniza** [comment]
o i see it was all under Filtering and Sorting Items. thx from the prompt answer man
