### ISSUE TITLE
reading variables from xrdb .xresources

### ISSUE THREAD

**Issue by beemo-ceniza** [themoken/canto-curses#49]
most curses based applications let you use variables from xrdb so if i change my colour theme i don't need to edit 10 different files, would it be possible to implement this?

**Comment by themoken** [comment]
Have you checked out the :color and :style commands in curses? You should be able to change your theme without _any_ hand edits...

https://codezen.org/canto-ng/manual/#Theming

**Comment by beemo-ceniza** [comment]
ye sure iv seen those options but they are internally to the program.

My current config has the main colors defined in an external file called xresources
> #define Blue #d0f7e5
> *.blue: Blue
Then for those programs that load variables directly for xresources file i just do:
> !urxvt
> URxvt.background: Blue
> !rofi
> rofi.color-window: Blue,    Blue,    Blue
for programs that define those variables internally:
polybar:
> blue = ${xrdb:*.blue}
i3-gaps:
> set_from_resource $blue  blue


The end result is that if i want to change some color i only need to edit one single variable making much simpler to maintain rather than having to edit 4 different files

**Comment by themoken** [comment]
Those are all X programs, this is curses. If there was a common curses color config, I'd jump on it, but it's up to your terminal emulator to honor xrdb and you can use it to map whatever color to one of the 16-256 available to curses, but canto still needs to be told which color code to use with :color
