### ISSUE TITLE
Implicit function declaration in widecurse.c - false alarm?

### ISSUE THREAD

**Issue by kozross** [themoken/canto-curses#51]
When building this package on Gentoo (modified ebuild to use latest version), I run across this warning message:

```
* QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * canto_curses/widecurse.c:63:4: warning: implicit declaration of function ‘waddwstr’; did you mean ‘waddstr’? [-Wimplicit-function-declaration]

 * Please do not file a Gentoo bug and instead report the above QA
 * issues directly to the upstream developers of this software.
 * Homepage: https://codezen.org/canto-ng/
```

This definitely appears to be a bug upstream, and the fix seems quite easy. Is this benign?

**Comment by themoken** [comment]
It's benign if the package properly linked in the end. 

[`waddwstr`](https://linux.die.net/man/3/waddwstr) is an ncursesw function. Somehow your `py_curses.h` (which pulls in `ncursesw.h` definitions) didn't include the `waddwstr` function protoype. Building on Arch I don't see that warn (although I do see some whinging from `py_curses.h` defining an unused variable). This might be a minor bug in ncurses headers (depending on the options Gentoo compiles it with) or in Python/py_curses headers but I don't think it makes sense to silence the warning (manually define the prototype) from `widecurse.c`
