### ISSUE TITLE
Font in reader

### ISSUE THREAD

**Issue by fn-ix** [themoken/canto-curses#52]
Hello!

I would like to know if there is any way to change the font of the text displayed in the reader. Reading longer articles in the terminal is rather tiresome with a typical small monospace console font.

**Comment by themoken** [comment]
The font is up to your terminal.

**Comment by fn-ix** [comment]
I would like to have the ability to only change the font of the feed's text body, while keeping the rest of the interface as the terminal standard. Is there a terminal emulator that could do this with canto?

**Comment by themoken** [comment]
Not that I know of, that would require some sort of context awareness from the terminal and that seems unlikely.

**Comment by fn-ix** [comment]
Ok, and to clarify, you are not able or willing to consider implementing it in the cantor reader itself?

**Comment by themoken** [comment]
It's not possible. Curses programs can only put characters on the screen, it's up to the terminal to decide how to display them. There may be hacks (like how a program can change the xterm title by printing a special code) but I'm unaware of any font controls at all.
-------- Original Message --------

**Comment by fn-ix** [comment]
Alright, thanks for the explanation.
