### ISSUE TITLE
Widecurse.c: invalid application of 'sizeof' to an incomplete type 'WINDOW'

### ISSUE THREAD

**Issue by leonryrko** [themoken/canto-curses#54]
I fail to install canto-curses following the [steps provided](https://codezen.org/canto-ng/source/#Git-Install). Besides of many warnings, I get the following error:

```
canto_curses/widecurse.c:83:28: error: invalid application of 'sizeof' to an incomplete type 'WINDOW' (aka 'struct _win_st')
        return Py_BuildValue("i", sizeof(WINDOW));
```

My Machine:
- macOS High Sierra 10.13.6
- Python 3.7.9 (built by Joyent's pkgsrc)
- Apple LLVM version 10.0.0 (clang-1000.10.44.4)

**Comment by themoken** [comment]
I don't support OSX or building with clang.

If I had to guess I'd say you're probably missing the ncursesw lib/headers though since WINDOW is an ncurses type, or you need to use GCC.
